name: 배포

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest # 작업이 실행될 환경
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3
      - name: 도커허브에 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 이미지 빌드
        run: docker buildx -t ${{ secrets.DOCKER_USERNAME }}/wandu-front
      - name: 도커허브에 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wandu-front
      - name: AWS EC2에 ssh 접속 후 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          port: 22
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "AWS 연결"
            docker pull ${{ secrets.DOCKER_USERNAME }}/wandu-front
            docker-compose up -d