name: 배포

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: 체크아웃
        uses: actions/checkout@v3

      # 2. 도커허브 로그인
      - name: 도커허브에 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 이미지 빌드
      - name: 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wandu-front .

      # 4. 도커허브에 이미지 푸시
      - name: 도커허브에 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wandu-front

      # 5. AWS EC2에 SSH 접속 후 배포
      - name: AWS EC2에 ssh 접속 후 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          port: 22
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "AWS 연결"

            # 기존 컨테이너 중지 및 제거 (실행 중이든 중지 상태든)
            if [ $(sudo docker ps -aq -f name=wandu-front) ]; then
              sudo docker stop wandu-front || true
              sudo docker rm wandu-front || true
            fi

            # 최신 이미지 가져오기
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/wandu-front

            # 사용하지 않는 이미지 정리
            sudo docker image prune -f

            # 컨테이너 실행 (포트 81)
            sudo docker run -d \
              --name wandu-front \
              -p 81:81 \
              ${{ secrets.DOCKER_USERNAME }}/wandu-front
